CREATE TABLE "instituicao" (
                               "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                               "nome" varchar,
                               "telefone" varchar,
                               "email" varchar UNIQUE,
                               "login" varchar UNIQUE,
                               "senha" varchar,
                               "tipo_usuario" varchar(5),
                               "deletado" boolean
);

CREATE TABLE "aluno" (
                         "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                         "nome" varchar,
                         "codigo" varchar UNIQUE,
                         "heroi_id" bigint,
                         "vogal_id" bigint NOT NULL,
                         "estagio" integer,
                         "professor_id" bigint NOT NULL,
                         "deletado" boolean
);

CREATE TABLE "heroi" (
                         "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                         "nome" varchar,
                         "icone" text,
                         "banner" text
);

CREATE TABLE "favorito" (
                            "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                            "jogo_id" bigint NOT NULL,
                            "aluno_id" bigint NOT NULL
);

CREATE TABLE "professor" (
                             "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                             "nome" varchar,
                             "imagem" text,
                             "email" varchar,
                             "instituicao_id" bigint NOT NULL,
                             "deletado" boolean
);

CREATE TABLE "jogo" (
                        "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                        "nome" varchar,
                        "descricao" varchar,
                        "estagio" integer,
                        "imagem" text,
                        "url" text,
                        "deletado" boolean
);

CREATE TABLE "historico" (
                             "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                             "aluno_id" bigint NOT NULL,
                             "jogo_id" bigint NOT NULL,
                             "minutos" integer,
                             "segundos" integer,
                             "concluido" boolean,
                             "pontos" integer,
                             "erros" integer
);

CREATE TABLE "vogal" (
                         "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                         "vogal" varchar(1)
);

CREATE TABLE "silaba" (
                          "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                          "vogal_id" bigint NOT NULL,
                          "silaba" varchar(3),
                          "palavra" text,
                          "complemento" text,
                          "som" text,
                          "deletado" boolean
);

CREATE TABLE "cena" (
                        "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                        "entidade_id" bigint NOT NULL,
                        "estagio" integer NOT NULL,
                        "cena" text,
                        "quantidade_certas" integer,
                        "quantidade_erradas" integer,
                        "deletado" boolean
);

CREATE TABLE "imagem" (
                          "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                          "silaba_id" bigint,
                          "palavra_id" bigint,
                          "imagem" text,
                          "descricao" text,
                          "colorir" integer,
                          "formato" integer,
                          "mascara" text,
                          "cena_id" bigint,
                          "deletado" boolean,
                          CONSTRAINT "chk_imagem_silaba_ou_palavra" CHECK (silaba_id IS NOT NULL OR palavra_id IS NOT NULL)
);

CREATE TABLE "fragmento" (
                             "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                             "caminho" text,
                             "imagem_id" bigint
);

CREATE TABLE "palavra" (
                           "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                           "palavra" text,
                           "som" text,
                           "deletado" boolean
);

CREATE TABLE "palavra_silaba" (
                                  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                  "palavra_id" bigint NOT NULL,
                                  "silaba_id" bigint NOT NULL,
                                  "posicao" integer
);

ALTER TABLE "aluno" ADD FOREIGN KEY ("heroi_id") REFERENCES "heroi" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "aluno" ADD FOREIGN KEY ("vogal_id") REFERENCES "vogal" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "aluno" ADD FOREIGN KEY ("professor_id") REFERENCES "professor" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "favorito" ADD FOREIGN KEY ("jogo_id") REFERENCES "jogo" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "favorito" ADD FOREIGN KEY ("aluno_id") REFERENCES "aluno" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "professor" ADD FOREIGN KEY ("instituicao_id") REFERENCES "instituicao" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "historico" ADD FOREIGN KEY ("aluno_id") REFERENCES "aluno" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "historico" ADD FOREIGN KEY ("jogo_id") REFERENCES "jogo" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "silaba" ADD FOREIGN KEY ("vogal_id") REFERENCES "vogal" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "imagem" ADD FOREIGN KEY ("silaba_id") REFERENCES "silaba" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "imagem" ADD FOREIGN KEY ("palavra_id") REFERENCES "palavra" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "imagem" ADD FOREIGN KEY ("cena_id") REFERENCES "cena" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "fragmento" ADD FOREIGN KEY ("imagem_id") REFERENCES "imagem" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "palavra_silaba" ADD FOREIGN KEY ("palavra_id") REFERENCES "palavra" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "palavra_silaba" ADD FOREIGN KEY ("silaba_id") REFERENCES "silaba" ("id") DEFERRABLE INITIALLY IMMEDIATE;
